version: "3"

services:
    apache:
        image: webdevops/php-apache:7.0
        ports:
          - "4500:80"
        volumes:
          - ./www:/app
    
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_HOST: '172.18.0.1'
            MYSQL_ROOT_PASSWORD: rootPWD
            #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            #MYSQL_USER: app
            #MYSQL_USER_PASS: !finalePass
        ports:
            - "3306"
        volumes:
            - ./db:/db


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: rootPWD
            PMA_ARBITRARY: 1
        ports:
          - "8088:80"

volumes:
    www:
    db:
