CREATE DATABASE IF NOT EXISTS mediaway;
USE mediaway;

CREATE TABLE IF NOT EXISTS brands(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS models(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(64) NOT NULL,
    min_HZ BIGINT NOT NULL,
    max_HZ BIGINT NOT NULL,
    idBrand INTEGER NOT NULL,

    FOREIGN KEY (idBrand) REFERENCES brands(id)
);

CREATE TABLE IF NOT EXISTS events(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(128) NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    start_day DATETIME NOT NULL,
    end_day DATETIME NOT NULL,
    description VARCHAR(4096) NOT NULL,
    opens_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS agencies(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(512) NOT NULL,
    pec VARCHAR(300) NOT NULL,
    name VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS reservations(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    idEvent INTEGER NOT NULL,
    idAgency INTEGER NOT NULL,

    FOREIGN KEY (idEvent) REFERENCES events(id),
    FOREIGN KEY (idAgency) REFERENCES agencies(id)
);

CREATE TABLE IF NOT EXISTS used_devices(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    frequency BIGINT NOT NULL,
    idReservation INTEGER NOT NULL,
    idModel INTEGER NOT NULL,

    FOREIGN KEY (idReservation) REFERENCES reservations(id),
    FOREIGN KEY (idModel) REFERENCES models(id),
);
